### ISSUE TITLE
Twitter new rules

### ISSUE THREAD

**Issue by jCHENEBY** [ELIXIR-NO/elixir-no-webpages#79]
The new limitation on twitter post view might cause problems for the twitter feed (if we are keeping it). 

On the current website the feed is not working.

More info here: https://www.techradar.com/computing/twitter/twitter-crisis-explained-what-are-rate-limits-and-when-will-they-end

**Comment by joshbaskaran** [comment]
I don’t believe we are keeping twitter around. The api requires a paid subscription and I i don’t think anyone cares about it enough to want to pay up. 

Also, there’s been some MAJOR redesign on this project that I have been working on. More on it soon ☺️

**Comment by jCHENEBY** [comment]
Very good point, the new twitter API rules and price seem like a nightmare.

Can't wait to see what you are working on!

**Comment by mdondrup** [comment]
Twitter is dead I suppose.
